### ISSUE TITLE
Update data url

### ISSUE THREAD

**Issue by jeroen** [ropenscilabs/ozflights#12]
Hi! This package no longer works because the data URL is 404.

The source seems to have changed. Can you update it to the 2018 data? https://www.bitre.gov.au/publications/ongoing/airport_traffic_data.aspx

**Comment by Lingtax** [comment]
There's apparently been some changes to the data structure and read in since last update.

1. data is now xlsx not xls
1. read_xlsx now indexes repeat column names by their column position (e.g. name...6, name...7) rather than "name", "name__1"
